// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/embedding/guest-layout.ts
/**
 * Route layout for the externally-hosted embedding guests.
 *
 * Importing the ui-embedding entry at module load registers the SDK's
 * embedding bootstrap before any guest calls getViewSDK(). The layout also
 * adds `.embedding-guest` to the document root so the shared app styles switch
 * to a transparent, chromeless surface (see styles.css). Each matched guest
 * renders through <router-outlet> and calls getViewSDK() for its SDK instance.
 */
// Registers the ui-embedding bootstrap at module load, before any guest
// calls getViewSDK().
import '@salesforce/platform-sdk/ui-embedding';

import { ChangeDetectionStrategy, Component, OnDestroy, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
	selector: 'app-guest-layout',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [RouterOutlet],
	template: '<router-outlet />',
})
export class GuestLayoutComponent implements OnInit, OnDestroy {
	ngOnInit(): void {
		document.documentElement.classList.add('embedding-guest');
	}

	ngOnDestroy(): void {
		document.documentElement.classList.remove('embedding-guest');
	}
}

// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/embedding/GuestLayout.tsx
/**
 * Route layout for the externally-hosted embedding recipes.
 *
 * Registers the ui-embedding bootstrap listener at module load and
 * applies the .embedding-guest class to the document root so shared
 * app styles switch to a transparent, chromeless layout. The matched
 * recipe renders through <Outlet /> and calls getViewSDK() to get its
 * SDK instance.
 */
// Registers the ui-embedding bootstrap listener at module load,
// before any recipe calls getViewSDK().
import '@salesforce/platform-sdk/ui-embedding';

import { useEffect } from 'react';
import { Outlet } from 'react-router';

export default function GuestLayout() {
  useEffect(() => {
    document.documentElement.classList.add('embedding-guest');
    return () => {
      document.documentElement.classList.remove('embedding-guest');
    };
  }, []);

  return <Outlet />;
}
