// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/embedding/receive-event/receive-event.ts
/**
 * Receive Event — live stock quote
 *
 * The mirror of SendToHost: here the host pushes an event *down* to the guest.
 * The LWC dispatches a `refreshticker` event on <lightning-ui-embedding>; the
 * guest hears it through viewSDK.addEventListener() and re-pulls the price.
 *
 * Why an event and not ui-state? Two channels, two jobs:
 *   - ui-state carries the Account's tickerSymbol — a Salesforce field the
 *     host owns and pushes (like every other recipe).
 *   - the share price is NOT in Salesforce. Only the guest can fetch it, so
 *     the host can't push it — it can only fire a `refreshticker` event that
 *     says "re-pull your own data now."
 *
 * This is fire-and-forget: the host doesn't wait for a result. A dispatched
 * event can't hand data back to its sender, so a reply would need the guest to
 * dispatch its own event the other direction.
 *
 * @see ReadHostDataComponent — receiving host-owned fields via ui-state
 * @see SendToHostComponent — dispatching events guest → host
 */
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, computed, signal } from '@angular/core';
import { getViewSDK } from '@salesforce/platform-sdk';
import { CardImports } from '../../../components/ui/card/card';
import { IconComponent } from '../../../components/ui/icon/icon';

interface AccountProps {
	recordId?: string;
	name?: string | null;
	tickerSymbol?: string | null;
}

interface Quote {
	price: number;
	asOf: string;
}

@Component({
	selector: 'app-receive-event',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [CardImports, IconComponent],
	templateUrl: './receive-event.html',
})
export class ReceiveEventComponent implements OnInit, OnDestroy {
	protected readonly account = signal<AccountProps>({});
	protected readonly quote = signal<Quote | null>(null);
	protected readonly refreshCount = signal(0);
	protected readonly connected = computed(() => Boolean(this.account().recordId));

	// The refresh listener reads this so it always re-pulls the current ticker
	// without re-subscribing every time ui-state changes.
	private currentTicker: string | null = null;
	private destroyed = false;
	private unsubscribe?: () => void;
	private detachRefresh?: () => void;

	ngOnInit(): void {
		getViewSDK().then((sdk) => {
			if (this.destroyed) return;

			// ui-state: which company are we looking at?
			const ui = sdk.getUiState?.();
			if (ui) {
				this.applyProps(ui.state.props as AccountProps);
				this.unsubscribe = ui.subscribe((next) => this.applyProps(next.props as AccountProps));
			}

			// Host → guest: the LWC fires `refreshticker`; re-pull the quote.
			const onRefresh = (): void => {
				const symbol = this.currentTicker;
				if (!symbol) return;
				this.fetchQuote(symbol).then((price) => {
					this.quote.set({ price, asOf: new Date().toLocaleTimeString() });
					this.refreshCount.update((count) => count + 1);
				});
			};
			sdk.addEventListener?.('refreshticker', onRefresh);
			this.detachRefresh = () => sdk.removeEventListener?.('refreshticker', onRefresh);
		});
	}

	ngOnDestroy(): void {
		this.destroyed = true;
		this.unsubscribe?.();
		this.detachRefresh?.();
	}

	// Apply host props and, when the ticker changes, seed a fresh quote.
	private applyProps(props: AccountProps): void {
		this.account.set(props);
		const symbol = props.tickerSymbol ?? null;
		if (symbol && symbol !== this.currentTicker) {
			this.currentTicker = symbol;
			this.fetchQuote(symbol).then((price) =>
				this.quote.set({ price, asOf: new Date().toLocaleTimeString() }),
			);
		}
	}

	// Stand-in for a real market feed. A production guest would fetch() its own
	// quote API here; we derive a stable base price from the symbol and add a
	// little jitter so each host refresh visibly moves the number.
	private async fetchQuote(symbol: string): Promise<number> {
		const base = [...symbol].reduce((sum, ch) => sum + ch.charCodeAt(0), 0) % 500;
		const jitter = (Math.random() - 0.5) * 4;
		return Math.max(1, base + jitter);
	}
}

// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/embedding/ReceiveEvent.tsx
/**
 * Receive Event — live stock quote
 *
 * The mirror of SendToHost: here the host pushes an event *down* to the
 * guest. The LWC dispatches a `refreshticker` event on
 * <lightning-ui-embedding>; the guest hears it through
 * viewSDK.addEventListener() and re-pulls.
 *
 * Why an event and not ui-state? Two channels, two jobs:
 *   - ui-state carries the Account's `tickerSymbol` — a Salesforce field
 *     the host owns and pushes (same as every other recipe).
 *   - the share price is NOT in Salesforce. Only the guest can fetch it,
 *     so the host can't push it — it can only fire a `refreshticker` event
 *     that says "re-pull your own data now."
 *
 * This is fire-and-forget: the host doesn't wait for a result. If the host
 * needed an answer ("did you accept this?"), the guest would have to dispatch
 * its own reply event — there's no synchronous return value across the bridge,
 * so a dispatched event can't hand data back to its sender. A `cancelable`
 * event doesn't help either: `preventDefault()` never reaches the host, because
 * the guest receives a fresh, non-cancelable copy of the event.
 *
 * @see ReadHostData — receiving host-owned fields via ui-state
 * @see SendToHost — dispatching events the other direction (guest → host)
 */
import { useEffect, useRef, useState } from 'react';
import { ExternalLink, TrendingUp } from 'lucide-react';
import { getViewSDK } from '@salesforce/platform-sdk';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

interface AccountProps {
  recordId?: string;
  name?: string | null;
  tickerSymbol?: string | null;
}

interface Quote {
  price: number;
  asOf: string;
}

export default function ReceiveEvent() {
  const [account, setAccount] = useState<AccountProps>({});
  const [quote, setQuote] = useState<Quote | null>(null);
  const [refreshCount, setRefreshCount] = useState(0);

  // The refresh listener closes over this ref so it always re-pulls the
  // current ticker without re-subscribing every time ui-state changes.
  const tickerRef = useRef<string | null>(null);

  useEffect(() => {
    let cleanup: (() => void) | undefined;
    let cancelled = false;

    // Apply host props and, when the ticker changes, seed a fresh quote.
    const applyProps = (props: AccountProps) => {
      setAccount(props);
      const symbol = props.tickerSymbol ?? null;
      if (symbol && symbol !== tickerRef.current) {
        tickerRef.current = symbol;
        fetchQuote(symbol).then(price =>
          setQuote({ price, asOf: new Date().toLocaleTimeString() })
        );
      }
    };

    getViewSDK().then(sdk => {
      if (cancelled) return;

      // ui-state: which company are we looking at?
      const ui = sdk.getUiState?.();
      if (ui) {
        applyProps(ui.state.props as AccountProps);
        cleanup = ui.subscribe(next => applyProps(next.props as AccountProps));
      }

      // Host → guest: the LWC fires `refreshticker`; re-pull the quote.
      const onRefresh = () => {
        const symbol = tickerRef.current;
        if (!symbol) return;
        fetchQuote(symbol).then(price => {
          setQuote({ price, asOf: new Date().toLocaleTimeString() });
          setRefreshCount(c => c + 1);
        });
      };
      sdk.addEventListener?.('refreshticker', onRefresh);

      const off = cleanup;
      cleanup = () => {
        off?.();
        sdk.removeEventListener?.('refreshticker', onRefresh);
      };
    });

    return () => {
      cancelled = true;
      cleanup?.();
    };
  }, []);

  const connected = Boolean(account.recordId);
  const { name, tickerSymbol } = account;

  return (
    <div className="p-4">
      <Card className="max-w-md">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-lg">
            <TrendingUp className="size-4" aria-hidden />
            {tickerSymbol ?? 'Stock quote'}
          </CardTitle>
          <CardDescription>
            {connected
              ? tickerSymbol
                ? `Live quote for ${name ?? 'this Account'}. The host fires a refreshticker event via viewSDK.addEventListener; the guest re-pulls the price.`
                : 'This Account has no ticker symbol.'
              : 'Drop this component on an Account record page to see a quote.'}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {tickerSymbol && quote && (
            <div className="flex items-baseline gap-2">
              <span className="text-3xl font-semibold tabular-nums">
                ${quote.price.toFixed(2)}
              </span>
              <span className="text-muted-foreground text-xs">
                as of {quote.asOf}
              </span>
            </div>
          )}

          {tickerSymbol && (
            <p className="text-muted-foreground text-xs">
              {refreshCount} refresh{refreshCount === 1 ? '' : 'es'} received
              from the host
            </p>
          )}
        </CardContent>
      </Card>
      <a
        href="https://github.com/trailheadapps/multiframework-recipes/blob/main/force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/embedding/ReceiveEvent.tsx"
        target="_blank"
        rel="noopener noreferrer"
        className="text-muted-foreground hover:text-primary mt-3 inline-flex items-center gap-1 text-xs"
      >
        Guest (ReceiveEvent.tsx)
        <ExternalLink className="size-3" aria-hidden />
      </a>
    </div>
  );
}

// Stand-in for a real market feed. A production guest would fetch() its own
// quote API here; we derive a stable base price from the symbol and add a
// little jitter so each host refresh visibly moves the number.
async function fetchQuote(symbol: string): Promise<number> {
  const base = [...symbol].reduce((sum, ch) => sum + ch.charCodeAt(0), 0) % 500;
  const jitter = (Math.random() - 0.5) * 4;
  return Math.max(1, base + jitter);
}
