// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/embedding/unsaved-changes/unsaved-changes.ts
/**
 * Unsaved Changes — editable form over host Account props.
 *
 * Calls viewSDK.markDirtyState() when the form diverges from the host's saved
 * values and clearDirtyState() when they match again. Salesforce then shows a
 * Save/Discard toolbar on the record page and warns before navigation while
 * dirty.
 *
 * Save dispatches `guestsave`; the host writes to Salesforce and pushes fresh
 * values back through ui-state. A `saving` guard stops rapid re-clicks from
 * firing duplicate updateRecords, and a short timeout releases the guard if the
 * host's save fails silently, so Save never sticks.
 *
 * @see SendToHostComponent, ReadHostDataComponent
 */
import {
	ChangeDetectionStrategy,
	Component,
	OnDestroy,
	OnInit,
	computed,
	effect,
	signal,
} from '@angular/core';
import { getViewSDK } from '@salesforce/platform-sdk';
import { ButtonImports } from '../../../components/ui/button/button';
import { CardImports } from '../../../components/ui/card/card';
import { IconComponent } from '../../../components/ui/icon/icon';
import { InputImports } from '../../../components/ui/input/input';
import { SelectImports, type AppSelectOption } from '../../../components/ui/select/select';

type Rating = 'Hot' | 'Warm' | 'Cold';

interface AccountProps {
	recordId?: string;
	name?: string | null;
	rating?: Rating | null;
	type?: string | null;
}

const RATING_OPTIONS: AppSelectOption[] = ['Hot', 'Warm', 'Cold'].map((r) => ({
	value: r,
	label: r,
}));

const TYPE_OPTIONS: AppSelectOption[] = [
	'Prospect',
	'Customer - Direct',
	'Customer - Channel',
	'Channel Partner / Reseller',
	'Technology Partner',
].map((t) => ({ value: t, label: t }));

@Component({
	selector: 'app-unsaved-changes',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ButtonImports, CardImports, IconComponent, InputImports, SelectImports],
	templateUrl: './unsaved-changes.html',
})
export class UnsavedChangesComponent implements OnInit, OnDestroy {
	protected readonly ratingOptions = RATING_OPTIONS;
	protected readonly typeOptions = TYPE_OPTIONS;

	protected readonly saved = signal<AccountProps>({});
	protected readonly form = signal<AccountProps>({});
	protected readonly connected = computed(() => Boolean(this.saved().recordId));
	protected readonly isDirty = computed(
		() =>
			this.form().name !== this.saved().name ||
			this.form().rating !== this.saved().rating ||
			this.form().type !== this.saved().type,
	);

	// Set once the host sends a payload with a recordId.
	private seeded = false;
	// Stops rapid Save re-clicks from firing duplicate updateRecords.
	private saving = false;
	// Failsafe: releases `saving` if the host never echoes back (its save failed).
	private saveTimeout?: ReturnType<typeof setTimeout>;
	private destroyed = false;
	private unsubscribe?: () => void;

	constructor() {
		// Mirror the form's dirty state to the host once the form is seeded.
		effect(() => {
			const dirty = this.isDirty();
			if (!this.seeded) return;
			getViewSDK().then((sdk) => {
				if (dirty) sdk.markDirtyState?.();
				else sdk.clearDirtyState?.();
			});
		});
	}

	ngOnInit(): void {
		getViewSDK().then((sdk) => {
			if (this.destroyed) return;
			const ui = sdk.getUiState?.();
			if (!ui) return;
			this.seed(ui.state.props as AccountProps);
			this.unsubscribe = ui.subscribe((next) => {
				this.seed(next.props as AccountProps);
				// Host echoed fresh values → the save round-trip completed.
				this.saving = false;
				if (this.saveTimeout) clearTimeout(this.saveTimeout);
			});
		});
	}

	ngOnDestroy(): void {
		this.destroyed = true;
		this.unsubscribe?.();
		if (this.saveTimeout) clearTimeout(this.saveTimeout);
	}

	private seed(props: AccountProps): void {
		// Adopt the host's values into the form when the user has nothing in
		// progress. That means the first payload, a form still matching the last
		// saved values, or the echo from our own save (which the host may
		// normalize). Otherwise keep the user's in-progress edits.
		const canAdopt = !this.seeded || !this.isDirty() || this.saving;
		this.saved.set(props);
		if (canAdopt) this.form.set(props);
		if (props.recordId) this.seeded = true;
	}

	protected setName(value: string): void {
		this.form.update((form) => ({ ...form, name: value }));
	}

	protected setRating(value: string): void {
		this.form.update((form) => ({ ...form, rating: (value || null) as Rating | null }));
	}

	protected setType(value: string): void {
		this.form.update((form) => ({ ...form, type: value || null }));
	}

	protected async save(): Promise<void> {
		if (this.saving) return;
		this.saving = true;
		const { name, rating, type } = this.form();
		const sdk = await getViewSDK();
		// All-lowercase, no hyphens, so the host LWC can bind it declaratively
		// (onguestsave) on the embedding element.
		sdk.dispatchEvent?.(
			new CustomEvent('guestsave', { detail: { name, rating, type }, bubbles: true }),
		);
		this.saveTimeout = setTimeout(() => {
			this.saving = false;
		}, 4000);
	}

	protected discard(): void {
		this.form.set(this.saved());
	}
}

// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/embedding/UnsavedChanges.tsx
/**
 * Unsaved Changes — editable form over host Account props.
 *
 * Calls viewSDK.markDirtyState() when the form diverges from the host's
 * saved values and clearDirtyState() when they match again. Salesforce
 * shows a Save/Discard toolbar on the record page and warns before
 * navigation while dirty.
 *
 * Save dispatches `guestsave`; the host writes to Salesforce and pushes
 * fresh values back through ui-state. The Save button stays clickable
 * throughout. An in-flight ref prevents rapid re-clicks from firing
 * duplicate updateRecords, and a short timeout releases that guard if the
 * host's save fails (it toasts without re-emitting), so Save never sticks.
 *
 * @see SendToHost, ReadHostData
 */
import { useEffect, useRef, useState } from 'react';
import { ExternalLink } from 'lucide-react';
import { getViewSDK } from '@salesforce/platform-sdk';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

type Rating = 'Hot' | 'Warm' | 'Cold';

interface AccountProps {
  recordId?: string;
  name?: string | null;
  rating?: Rating | null;
  type?: string | null;
}

const RATINGS: Rating[] = ['Hot', 'Warm', 'Cold'];
const TYPES = [
  'Prospect',
  'Customer - Direct',
  'Customer - Channel',
  'Channel Partner / Reseller',
  'Technology Partner',
];

export default function UnsavedChanges() {
  const [saved, setSaved] = useState<AccountProps>({});
  const [form, setForm] = useState<AccountProps>({});
  // Mirrors `saved` so the ui-state subscription can compare against the last
  // saved values synchronously (the state captured in that closure is stale).
  const savedRef = useRef<AccountProps>({});
  // Set once the host sends a payload with a recordId.
  const seededRef = useRef(false);
  // Prevents rapid Save re-clicks from firing duplicate updateRecords.
  // The button stays clickable so its state doesn't dirty → clean → dirty
  // flicker while the host round-trips.
  const savingRef = useRef(false);
  // Failsafe timer: releases `savingRef` if the host never echoes back
  // (e.g. its updateRecord failed), so a failed save doesn't lock the button.
  const saveTimeoutRef = useRef<number | undefined>(undefined);

  useEffect(() => {
    let unsubscribe: (() => void) | undefined;
    let cancelled = false;
    getViewSDK().then(sdk => {
      if (cancelled) return;
      const ui = sdk.getUiState?.();
      if (!ui) return;
      const seed = (p: AccountProps) => {
        // Adopt the host's values into the form when the user has nothing in
        // progress. That means the first payload, a form still matching the last
        // saved values, or the echo from our own save (which the host may
        // normalize). Otherwise keep the user's in-progress edits.
        const prevSaved = savedRef.current;
        const wasSeeded = seededRef.current;
        const wasSaving = savingRef.current;
        savedRef.current = p;
        if (p.recordId) seededRef.current = true;
        setSaved(p);
        setForm(prevForm => {
          const pristine =
            prevForm.name === prevSaved.name &&
            prevForm.rating === prevSaved.rating &&
            prevForm.type === prevSaved.type;
          return !wasSeeded || pristine || wasSaving ? p : prevForm;
        });
      };
      seed(ui.state.props as AccountProps);
      unsubscribe = ui.subscribe(latest => {
        seed(latest.props as AccountProps);
        // Host echoed fresh values → the save round-trip completed.
        savingRef.current = false;
        if (saveTimeoutRef.current) window.clearTimeout(saveTimeoutRef.current);
      });
    });
    return () => {
      cancelled = true;
      unsubscribe?.();
      if (saveTimeoutRef.current) window.clearTimeout(saveTimeoutRef.current);
    };
  }, []);

  const isDirty =
    form.name !== saved.name ||
    form.rating !== saved.rating ||
    form.type !== saved.type;
  const connected = Boolean(saved.recordId);

  useEffect(() => {
    if (!seededRef.current) return;
    getViewSDK().then(sdk => {
      if (isDirty) void sdk.markDirtyState?.();
      else void sdk.clearDirtyState?.();
    });
  }, [isDirty]);

  function set<K extends keyof AccountProps>(key: K, value: AccountProps[K]) {
    setForm(prev => ({ ...prev, [key]: value }));
  }

  async function handleSave() {
    if (savingRef.current) return;
    savingRef.current = true;
    // Event name is all-lowercase with no hyphens so the host LWC can
    // bind it declaratively (`onguestsave={handleSave}` on the outer div).
    const sdk = await getViewSDK();
    sdk.dispatchEvent?.(
      new CustomEvent('guestsave', {
        detail: { name: form.name, rating: form.rating, type: form.type },
        bubbles: true,
      })
    );
    // The host normally releases the guard by echoing fresh values via
    // ui-state. If its updateRecord fails (it surfaces a toast and doesn't
    // re-emit), release after a short delay so a failed save can be retried.
    saveTimeoutRef.current = window.setTimeout(() => {
      savingRef.current = false;
    }, 4000);
  }

  function handleDiscard() {
    setForm(saved);
  }

  return (
    <div className="p-1">
      <Card className="max-w-md">
        <CardHeader>
          <CardTitle className="text-lg">Edit Account</CardTitle>
          <CardDescription>
            {connected
              ? 'Edit any field. Watch the host badge track your changes.'
              : 'Drop this component on an Account record page to edit.'}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-1.5">
            <label htmlFor="unsaved-name" className="text-sm font-medium">
              Name
            </label>
            <Input
              id="unsaved-name"
              type="text"
              value={form.name ?? ''}
              onChange={e => set('name', e.target.value)}
            />
          </div>

          <div className="grid gap-1.5">
            <label htmlFor="unsaved-rating" className="text-sm font-medium">
              Rating
            </label>
            <Select
              value={form.rating ?? ''}
              onValueChange={value => set('rating', value as Rating)}
            >
              <SelectTrigger id="unsaved-rating" className="w-full">
                <SelectValue placeholder="Choose rating" />
              </SelectTrigger>
              <SelectContent>
                {RATINGS.map(r => (
                  <SelectItem key={r} value={r}>
                    {r}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="grid gap-1.5">
            <label htmlFor="unsaved-type" className="text-sm font-medium">
              Type
            </label>
            <Select
              value={form.type ?? ''}
              onValueChange={value => set('type', value)}
            >
              <SelectTrigger id="unsaved-type" className="w-full">
                <SelectValue placeholder="Choose type" />
              </SelectTrigger>
              <SelectContent>
                {TYPES.map(t => (
                  <SelectItem key={t} value={t}>
                    {t}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex gap-2 pt-2">
            <Button size="sm" onClick={handleSave}>
              Save
            </Button>
            <Button size="sm" variant="outline" onClick={handleDiscard}>
              Discard
            </Button>
          </div>
        </CardContent>
      </Card>
      <a
        href="https://github.com/trailheadapps/multiframework-recipes/blob/main/force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/embedding/UnsavedChanges.tsx"
        target="_blank"
        rel="noopener noreferrer"
        className="text-muted-foreground hover:text-primary mt-3 inline-flex items-center gap-1 text-xs"
      >
        Guest (UnsavedChanges.tsx)
        <ExternalLink className="size-3" aria-hidden />
      </a>
    </div>
  );
}
