// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/styling/account-card-slds/account-card-slds.ts
import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { createDataSDK, gql } from '@salesforce/platform-sdk';
import { SldsScopeComponent } from '../../../components/app/slds-scope/slds-scope';

const QUERY = gql`
	query GetFirstAccount {
		uiapi {
			query {
				Account(first: 1) {
					edges {
						node {
							Id
							Name @optional {
								value
							}
							Industry @optional {
								value
							}
							AnnualRevenue @optional {
								value
							}
						}
					}
				}
			}
		}
	}
`;

/**
 * Account Card — SLDS Blueprint
 *
 * Displays Account data with SLDS blueprint classes on plain markup — the manual
 * equivalent of <lightning-card>, where you own the structure. The header icon
 * comes from the SLDS standard sprite.
 *
 * @see AccountCardShadcnComponent — the same card with the app's spartan-ng card
 */
@Component({
	selector: 'app-account-card-slds',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [SldsScopeComponent],
	templateUrl: './account-card-slds.html',
})
export class AccountCardSldsComponent implements OnInit {
	protected readonly account = signal<AccountFields | undefined>(undefined);
	protected readonly loading = signal(true);
	protected readonly error = signal<string | undefined>(undefined);

	async ngOnInit(): Promise<void> {
		try {
			const sdk = await createDataSDK();
			const result = await sdk.graphql?.query<QueryResponse>({ query: QUERY });

			if (result?.errors?.length) {
				throw new Error(result.errors.map((e: { message: string }) => e.message).join('; '));
			}

			const node = result?.data?.uiapi?.query?.Account?.edges?.[0]?.node;
			if (node) {
				this.account.set({
					name: node.Name?.value ?? 'Unknown',
					industry: node.Industry?.value ?? null,
					revenue: formatRevenue(node.AnnualRevenue?.value),
				});
			}
		} catch (err) {
			this.error.set(err instanceof Error ? err.message : 'Request failed');
		} finally {
			this.loading.set(false);
		}
	}
}

function formatRevenue(value: number | null | undefined): string {
	if (value == null) return '—';
	return new Intl.NumberFormat('en-US', {
		style: 'currency',
		currency: 'USD',
		notation: 'compact',
		maximumFractionDigits: 1,
	}).format(value);
}

interface QueryResponse {
	uiapi: {
		query: {
			Account: {
				edges: {
					node: {
						Id: string;
						Name: { value: string | null };
						Industry: { value: string | null };
						AnnualRevenue: { value: number | null };
					};
				}[];
			};
		};
	};
}

interface AccountFields {
	name: string;
	industry: string | null;
	revenue: string;
}

// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/styling/AccountCardSLDS.tsx
/**
 * Account Card — SLDS Blueprint
 *
 * Displays Account data using SLDS blueprint CSS classes on plain JSX markup.
 * The manual equivalent of <lightning-card> -- you own the markup structure.
 *
 * @see AccountCardShadcn — same card with shadcn/ui components
 */
import { useFirstAccount } from '@/api/account';

export default function AccountCardSLDS() {
  const { account, loading, error } = useFirstAccount();

  if (loading) return <p className="slds-text-body_regular">Loading…</p>;
  if (error) return <p className="slds-text-color_error">{error}</p>;
  if (!account)
    return <p className="slds-text-color_weak">No account found.</p>;

  return (
    <article className="slds-card">
      {/* Header: icon + title */}
      <div className="slds-card__header slds-grid">
        <header className="slds-media slds-media_center slds-has-flexi-truncate">
          <div className="slds-media__figure">
            {/* slds-icon-standard-account applies the object color background.
                Each standard object has its own class: slds-icon-standard-contact, etc. */}
            <span
              className="slds-icon_container slds-icon-standard-account"
              title="Account"
            >
              <svg className="slds-icon slds-icon_small" aria-hidden="true">
                <use href="/assets/icons/standard-sprite/svg/symbols.svg#account" />
              </svg>
              <span className="slds-assistive-text">Account</span>
            </span>
          </div>
          <div className="slds-media__body">
            <h2 className="slds-card__header-title">
              <span className="slds-truncate" title={account.Name?.value ?? ''}>
                {account.Name?.value}
              </span>
            </h2>
          </div>
        </header>
      </div>

      {/* Body: key/value field list */}
      <div className="slds-card__body slds-card__body_inner">
        {/* slds-list_horizontal slds-wrap: SLDS pattern for key/value field detail layout */}
        <dl className="slds-list_horizontal slds-wrap">
          <dt
            className="slds-item_label slds-text-color_weak slds-truncate"
            title="Industry"
          >
            Industry
          </dt>
          <dd className="slds-item_detail slds-truncate">
            {account.Industry?.value ?? '—'}
          </dd>

          <dt
            className="slds-item_label slds-text-color_weak slds-truncate"
            title="Annual Revenue"
          >
            Annual Revenue
          </dt>
          <dd className="slds-item_detail slds-truncate">
            {formatRevenue(account.AnnualRevenue?.value)}
          </dd>
        </dl>
      </div>

      {/* Footer */}
      <footer className="slds-card__footer">
        <a className="slds-card__footer-action" href="#">
          View Account
        </a>
      </footer>
    </article>
  );
}

function formatRevenue(value: number | null | undefined): string {
  if (value == null) return '—';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    notation: 'compact',
    maximumFractionDigits: 1,
  }).format(value);
}
