// force-app/main/react-recipes/uiBundles/reactRecipes/src/components/app/SldsScope.tsx
import type { ReactNode } from 'react';

/**
 * Wraps SLDS 2 blueprint markup in the required `.slds-scope` container.
 *
 * The app loads the SLDS 2 *scoped* stylesheet, which only styles elements
 * inside `.slds-scope`. This keeps SLDS out of the Tailwind/shadcn app shell —
 * put SLDS blueprint recipes inside <SldsScope>, leave everything else outside.
 */
export default function SldsScope({ children }: { children: ReactNode }) {
  return <div className="slds-scope">{children}</div>;
}

// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/components/app/slds-scope/slds-scope.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

/**
 * SLDS Scope
 *
 * Wraps SLDS 2 blueprint markup in the required `.slds-scope` container. SLDS 2
 * is consumed scoped (see styles.css), so its blueprint classes only take effect
 * inside a `.slds-scope` element — which keeps SLDS out of the Tailwind/spartan
 * app shell. Put SLDS blueprint recipes inside <app-slds-scope>; leave the
 * spartan-ng recipes and app chrome outside it.
 */
@Component({
	selector: 'app-slds-scope',
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: '<div class="slds-scope"><ng-content /></div>',
})
export class SldsScopeComponent {}
