// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/error-handling/GraphqlErrors.tsx
/**
 * GraphQL Error Handling
 *
 * Executes a query that intentionally requests a nonexistent field to trigger
 * a GraphQL error. UIAPI surfaces these in result.errors[] rather than
 * throwing — run both queries to see the difference between query-level
 * errors and thrown exceptions.
 *
 * LWC equivalent: @wire with the graphql adapter provides errors via the
 * error property. Imperative calls return errors in the result object.
 *
 * @see ErrorBoundaryRecipe — catching render-time JavaScript errors
 */
import { useState } from 'react';
import { createDataSDK, gql } from '@salesforce/platform-sdk';
import { Button } from '@/components/ui/button';

// This query intentionally asks for a field that doesn't exist on Account.
// UIAPI will return a result.errors[] array rather than throwing an exception.
const BAD_QUERY = `
  query BadAccountQuery {
    uiapi {
      query {
        Account(first: 1) {
          edges {
            node {
              Id
              NonExistentField__c { value }
            }
          }
        }
      }
    }
  }
`;

const GOOD_QUERY = gql`
  query GoodAccountQuery {
    uiapi {
      query {
        Account(first: 1) {
          edges {
            node {
              Id
              Name @optional {
                value
              }
            }
          }
        }
      }
    }
  }
`;

interface GraphQLError {
  message: string;
  locations?: Array<{ line: number; column: number }>;
  path?: string[];
}

export default function GraphqlErrors() {
  const [errors, setErrors] = useState<GraphQLError[]>();
  const [success, setSuccess] = useState<string>();
  const [loading, setLoading] = useState(false);

  async function runQuery(query: string, label: string) {
    setLoading(true);
    setErrors(undefined);
    setSuccess(undefined);

    try {
      const sdk = await createDataSDK();
      const result = await sdk.graphql?.query({ query });

      // Layer 1: result.errors[] — query-level errors (bad fields, auth, etc.)
      if (result?.errors?.length) {
        setErrors(result.errors);
        return;
      }

      setSuccess(`${label} succeeded — no errors.`);
    } catch (err) {
      // Layer 2: thrown exceptions — network failures, SDK errors
      setErrors([
        {
          message: err instanceof Error ? err.message : 'Request failed',
        },
      ]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <div className="flex gap-2 mb-2">
        <Button
          variant="outline"
          className="border-rose-300 text-rose-600 hover:bg-rose-50"
          onClick={() => runQuery(BAD_QUERY, 'Bad query')}
          disabled={loading}
        >
          Run Bad Query
        </Button>
        <Button
          onClick={() => runQuery(GOOD_QUERY, 'Good query')}
          disabled={loading}
        >
          Run Good Query
        </Button>
      </div>

      {loading && <p className="text-sm">Executing…</p>}

      {errors && (
        <div
          className="rounded-md bg-rose-50 border border-rose-200 p-4 text-rose-700"
          role="alert"
        >
          <p className="text-xs mb-1">
            <strong>
              {errors.length} error{errors.length > 1 ? 's' : ''} returned
            </strong>
          </p>
          <ul className="list-disc pl-5">
            {errors.map((e, i) => (
              <li key={i} className="text-xs">
                {e.message}
                {e.path && (
                  <span className="text-muted-foreground">
                    {' '}
                    — path: {e.path.join('.')}
                  </span>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}

      {success && (
        <div
          className="rounded-md bg-emerald-50 border border-emerald-200 p-4 text-emerald-700"
          role="status"
        >
          <p className="text-xs">{success}</p>
        </div>
      )}
    </div>
  );
}

// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/error-handling/graphql-errors/graphql-errors.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { createDataSDK, gql } from '@salesforce/platform-sdk';
import { ButtonImports } from '../../../components/ui/button/button';

// Intentionally asks for a field that doesn't exist on Account. UIAPI returns
// a result.errors[] array rather than throwing — so it's a plain string, not a
// gql tag (there's nothing valid to highlight).
const BAD_QUERY = `
	query BadAccountQuery {
		uiapi {
			query {
				Account(first: 1) {
					edges {
						node {
							Id
							NonExistentField__c {
								value
							}
						}
					}
				}
			}
		}
	}
`;

const GOOD_QUERY = gql`
	query GoodAccountQuery {
		uiapi {
			query {
				Account(first: 1) {
					edges {
						node {
							Id
							Name @optional {
								value
							}
						}
					}
				}
			}
		}
	}
`;

/**
 * GraphQL Error Handling
 *
 * Runs a query that requests a nonexistent field. UIAPI surfaces such problems
 * in result.errors[] (each with a message and often a path) rather than
 * throwing — so there are two layers to handle: query-level errors you read off
 * the result, and thrown exceptions (network/SDK) you catch. Run both queries
 * to see the difference.
 *
 * LWC equivalent: @wire with the GraphQL adapter hands you problems via its
 * error property; here you read them off result.errors[] yourself.
 *
 * @see ErrorBoundaryComponent — containing render-time exceptions
 */
@Component({
	selector: 'app-graphql-errors',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ButtonImports],
	templateUrl: './graphql-errors.html',
})
export class GraphqlErrorsComponent {
	protected readonly errors = signal<GraphqlError[] | undefined>(undefined);
	protected readonly success = signal<string | undefined>(undefined);
	protected readonly loading = signal(false);

	protected runBad(): void {
		this.run(BAD_QUERY, 'Bad query');
	}

	protected runGood(): void {
		this.run(GOOD_QUERY, 'Good query');
	}

	private async run(query: string, label: string): Promise<void> {
		this.loading.set(true);
		this.errors.set(undefined);
		this.success.set(undefined);
		try {
			const sdk = await createDataSDK();
			const result = await sdk.graphql?.query({ query });

			// Layer 1: query-level errors (bad fields, auth, etc.) — returned, not thrown.
			if (result?.errors?.length) {
				this.errors.set(
					result.errors.map((e: GraphqlError) => ({ message: e.message, path: e.path })),
				);
				return;
			}

			this.success.set(`${label} succeeded — no errors.`);
		} catch (err) {
			// Layer 2: thrown exceptions — network failures, SDK errors.
			this.errors.set([{ message: err instanceof Error ? err.message : 'Request failed' }]);
		} finally {
			this.loading.set(false);
		}
	}
}

interface GraphqlError {
	message: string;
	// UIAPI usually includes the path to the offending field, e.g.
	// ["uiapi","query","Account"]. Thrown (network/SDK) errors have no path.
	path?: string[];
}
