// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/hello/BindingAccountName.tsx
/**
 * Binding to an Account Name
 *
 * Fetches an Account via UIAPI GraphQL and binds the Name field to the UI.
 * In LWC, template expressions track reactive properties automatically; here
 * useState drives re-renders when data arrives. The { value } wrapper on every
 * field mirrors record.fields.Name.value from @wire(getRecord) — same UIAPI shape.
 *
 * LWC equivalent: @wire(getRecord) with a field list, then access
 * record.fields.Name.value in the template. useState here plays the role
 * of @track (reactive properties).
 *
 * @see ConditionalStatus — conditional rendering with picklist data
 */
import { useEffect, useState } from 'react';
import { createDataSDK, gql } from '@salesforce/platform-sdk';

// Every scalar field in UIAPI GraphQL is wrapped in { value }.
// This is different from standard GraphQL where fields are plain scalars.
const QUERY = gql`
  query FirstAccountName {
    uiapi {
      query {
        Account(first: 1, orderBy: { Name: { order: ASC } }) {
          edges {
            node {
              Id
              Name @optional {
                value
              }
            }
          }
        }
      }
    }
  }
`;

interface QueryResponse {
  uiapi: {
    query: {
      Account: {
        edges: Array<{
          node: { Id: string; Name: { value: string | null } };
        }>;
      };
    };
  };
}

export default function BindingAccountName() {
  const [name, setName] = useState<string>();
  const [error, setError] = useState<string>();

  useEffect(() => {
    const fetchName = async () => {
      const sdk = await createDataSDK();
      const result = await sdk.graphql?.query<QueryResponse>({ query: QUERY });

      if (result?.errors?.length) {
        throw new Error(
          result.errors.map((e: { message: string }) => e.message).join('; ')
        );
      }

      const node = result?.data?.uiapi?.query?.Account?.edges?.[0]?.node;
      // Unwrap the { value } wrapper — Salesforce's UIAPI wraps every field
      setName(node?.Name?.value ?? 'Unknown');
    };

    fetchName().catch(err => {
      setError(err instanceof Error ? err.message : 'Request failed');
    });
  }, []);

  if (error) return <p className="text-destructive">{error}</p>;

  return <p className="text-lg font-semibold">{name ?? 'Loading…'}</p>;
}

// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/hello/binding-account-name/binding-account-name.ts
import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { createDataSDK, gql } from '@salesforce/platform-sdk';

// Every scalar field in UIAPI GraphQL is wrapped in { value }. This is different
// from standard GraphQL, where fields are plain scalars.
const QUERY = gql`
	query FirstAccountName {
		uiapi {
			query {
				Account(first: 1, orderBy: { Name: { order: ASC } }) {
					edges {
						node {
							Id
							Name @optional {
								value
							}
						}
					}
				}
			}
		}
	}
`;

/**
 * Binding to an Account Name
 *
 * Fetches an Account via UIAPI GraphQL and binds the Name field to the template.
 * A signal drives re-render when the data arrives, and the { value } wrapper on
 * every field mirrors record.fields.Name.value from @wire(getRecord).
 *
 * LWC equivalent: @wire(getRecord) with a field list, then read
 * record.fields.Name.value in the template. A signal here plays the role of a
 * reactive @track property.
 *
 * @see ConditionalStatusComponent — conditional rendering with picklist data
 */
@Component({
	selector: 'app-binding-account-name',
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './binding-account-name.html',
})
export class BindingAccountNameComponent implements OnInit {
	protected readonly name = signal<string | undefined>(undefined);
	protected readonly error = signal<string | undefined>(undefined);

	async ngOnInit(): Promise<void> {
		try {
			const sdk = await createDataSDK();
			const result = await sdk.graphql?.query<QueryResponse>({ query: QUERY });

			if (result?.errors?.length) {
				throw new Error(
					result.errors.map((e: { message: string }) => e.message).join('; '),
				);
			}

			const node = result?.data?.uiapi?.query?.Account?.edges?.[0]?.node;
			// Unwrap the { value } wrapper — Salesforce's UIAPI wraps every field.
			this.name.set(node?.Name?.value ?? 'Unknown');
		} catch (err) {
			this.error.set(err instanceof Error ? err.message : 'Request failed');
		}
	}
}

interface QueryResponse {
	uiapi: {
		query: {
			Account: {
				edges: { node: { Id: string; Name: { value: string | null } } }[];
			};
		};
	};
}
