// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/hello/HelloWorld.tsx
/**
 * Hello World
 *
 * The simplest possible Salesforce web application component — a plain React
 * function component.
 *
 * @see BindingAccountName — fetching and binding Salesforce data
 */
export default function HelloWorld() {
  const greeting = 'World';

  return <p className="text-sm">Hello, {greeting}!</p>;
}

// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/hello/hello-world/hello-world.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

/**
 * Hello World
 *
 * The simplest possible Salesforce web application component — a plain Angular
 * standalone component that renders a bound expression.
 *
 * @see BindingAccountNameComponent — fetching and binding Salesforce data
 */
@Component({
	selector: 'app-hello-world',
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './hello-world.html',
})
export class HelloWorldComponent {
	protected readonly greeting = 'World';
}
