// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/integration/SearchableAccountList.tsx
/**
 * Searchable Account List
 *
 * A controlled search input drives a GraphQL variable that filters
 * Accounts by name. A debounce timer prevents firing a query on every
 * keystroke — the query only runs after the user stops typing.
 *
 * Key Concepts:
 * - Debounced search: wait for the user to stop typing before querying
 * - Combining query variables with user input via the `like` operator
 * - Controlled input bound to search state
 *
 * Demonstrates: combining variables, imperative refetch, loading states,
 * and debounce in a single cohesive pattern.
 *
 * LWC equivalent: a @track property with a debounce timer passed to @wire
 * with the graphql adapter. The wire re-fires when the variable changes.
 *
 * @see DashboardAliasedQueries — combining aliased queries for dashboards
 */
import { useEffect, useState, useRef, useCallback } from 'react';
import { createDataSDK, gql } from '@salesforce/platform-sdk';
import { Input } from '@/components/ui/input';

// The $name variable drives the `like` filter. Passing "%%" matches all.
const QUERY = gql`
  query SearchAccounts($name: String = "%%") {
    uiapi {
      query {
        Account(
          first: 10
          where: { Name: { like: $name } }
          orderBy: { Name: { order: ASC } }
        ) {
          edges {
            node {
              Id
              Name @optional {
                value
              }
              Industry @optional {
                value
              }
            }
          }
        }
      }
    }
  }
`;

interface QueryResponse {
  uiapi: {
    query: {
      Account: {
        edges: Array<{
          node: {
            Id: string;
            Name: { value: string | null };
            Industry: { value: string | null };
          };
        }>;
      };
    };
  };
}

interface AccountFields {
  id: string;
  name: string;
  industry: string | null;
}

export default function SearchableAccountList() {
  const [search, setSearch] = useState('');
  const [accounts, setAccounts] = useState<AccountFields[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>();
  const debounceRef = useRef<ReturnType<typeof setTimeout>>(undefined);

  const fetchAccounts = useCallback(async (term: string) => {
    setLoading(true);
    setError(undefined);

    try {
      const sdk = await createDataSDK();
      // Wrap the search term in wildcards for the `like` operator
      const result = await sdk.graphql?.query<QueryResponse>({
        query: QUERY,
        variables: { name: term ? `%${term}%` : '%%' },
      });

      if (result?.errors?.length) {
        throw new Error(
          result.errors.map((e: { message: string }) => e.message).join('; ')
        );
      }

      const edges = result?.data?.uiapi?.query?.Account?.edges ?? [];
      setAccounts(
        edges
          .map(edge => edge?.node)
          .filter(Boolean)
          .map(node => ({
            id: node.Id,
            name: node.Name?.value ?? 'Unknown',
            industry: node.Industry?.value ?? null,
          }))
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Request failed');
    } finally {
      setLoading(false);
    }
  }, []);

  // Fetch all accounts on mount
  useEffect(() => {
    fetchAccounts('');
  }, [fetchAccounts]);

  // Debounce: wait 350ms after the user stops typing before querying
  function handleSearchChange(value: string) {
    setSearch(value);
    clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      fetchAccounts(value);
    }, 350);
  }

  return (
    <div>
      <div className="space-y-1 mb-2">
        <Input
          type="text"
          placeholder="Search accounts by name…"
          value={search}
          onChange={e => handleSearchChange(e.target.value)}
        />
      </div>

      {error && <p className="text-destructive">{error}</p>}

      {loading && <p className="text-sm text-muted-foreground">Searching…</p>}

      {!loading && !error && accounts.length === 0 && (
        <p className="text-sm text-muted-foreground">
          No accounts match &ldquo;{search}&rdquo;
        </p>
      )}

      {!loading && !error && accounts.length > 0 && (
        <div className="rounded-md border border-border bg-card p-4 shadow-sm">
          <ul>
            {accounts.map(account => (
              <li
                key={account.id}
                className="py-2 -mx-2 px-2 rounded-md transition-colors hover:bg-accent/50"
              >
                <p className="text-sm text-foreground">{account.name}</p>
                {account.industry && (
                  <p className="text-xs text-muted-foreground">
                    {account.industry}
                  </p>
                )}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/integration/searchable-account-list/searchable-account-list.ts
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, signal } from '@angular/core';
import { createDataSDK, gql } from '@salesforce/platform-sdk';
import { InputImports } from '../../../components/ui/input/input';

// The $name variable drives the `like` filter; the "%%" default matches all,
// so the list is fully populated on first load before the user types.
const QUERY = gql`
	query SearchAccounts($name: String = "%%") {
		uiapi {
			query {
				Account(first: 10, where: { Name: { like: $name } }, orderBy: { Name: { order: ASC } }) {
					edges {
						node {
							Id
							Name @optional {
								value
							}
							Industry @optional {
								value
							}
						}
					}
				}
			}
		}
	}
`;

/**
 * Searchable Account List
 *
 * A controlled, debounced search input drives a GraphQL variable that filters
 * Accounts by name — combining variables, imperative refetch, loading states,
 * and debounce in one cohesive pattern.
 *
 * LWC equivalent: a @track property with a debounce timer passed to @wire; the
 * wire re-fires when the variable changes.
 *
 * @see DashboardAliasedQueriesComponent — aliased queries for a dashboard
 */
@Component({
	selector: 'app-searchable-account-list',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [InputImports],
	templateUrl: './searchable-account-list.html',
})
export class SearchableAccountListComponent implements OnInit, OnDestroy {
	protected readonly search = signal('');
	protected readonly accounts = signal<AccountFields[]>([]);
	protected readonly loading = signal(true);
	protected readonly error = signal<string | undefined>(undefined);

	private timer?: ReturnType<typeof setTimeout>;
	// Monotonic id so a slow earlier request can't overwrite a newer one — the
	// mount fetch('') and a debounced fetch(term) can be in flight at once.
	private requestId = 0;

	ngOnInit(): void {
		this.fetch('');
	}

	protected onSearch(value: string): void {
		this.search.set(value);
		clearTimeout(this.timer);
		this.timer = setTimeout(() => this.fetch(value), 350);
	}

	ngOnDestroy(): void {
		clearTimeout(this.timer);
	}

	private async fetch(term: string): Promise<void> {
		const id = ++this.requestId;
		this.loading.set(true);
		this.error.set(undefined);
		try {
			const sdk = await createDataSDK();
			const result = await sdk.graphql?.query<QueryResponse>({
				query: QUERY,
				variables: { name: term ? `%${term}%` : '%%' },
			});

			// A newer search started while this one was in flight — drop the stale result.
			if (id !== this.requestId) return;

			if (result?.errors?.length) {
				throw new Error(result.errors.map((e: { message: string }) => e.message).join('; '));
			}

			const edges = result?.data?.uiapi?.query?.Account?.edges ?? [];
			this.accounts.set(
				edges
					.map((edge) => edge?.node)
					.filter((node): node is AccountNode => node != null)
					.map((node) => ({
						id: node.Id,
						name: node.Name?.value ?? 'Unknown',
						industry: node.Industry?.value ?? null,
					})),
			);
		} catch (err) {
			if (id !== this.requestId) return;
			this.error.set(err instanceof Error ? err.message : 'Request failed');
		} finally {
			if (id === this.requestId) this.loading.set(false);
		}
	}
}

interface AccountNode {
	Id: string;
	Name: { value: string | null };
	Industry: { value: string | null };
}

interface QueryResponse {
	uiapi: {
		query: {
			Account: {
				edges: { node: AccountNode }[];
			};
		};
	};
}

interface AccountFields {
	id: string;
	name: string;
	industry: string | null;
}
