// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/integration/DashboardAliasedQueries.tsx
/**
 * Dashboard with Aliased Queries
 *
 * Fetches Accounts, Contacts, and Opportunities in a single GraphQL
 * request using aliases. Transforms the results into stat cards that
 * form a simple dashboard layout.
 *
 * Key Concepts:
 * - Combining aliased multi-object queries for dashboard patterns
 * - Three aliases in one request reduces network round-trips
 * - Layout composition with reusable StatCard components
 * - Data transformation from GraphQL edges to display values
 *
 * Demonstrates: combining aliased multi-object queries with layout
 * composition and data transformation helpers.
 *
 * LWC equivalent: multiple @wire calls or an Apex method returning
 * a wrapper object with counts for each object type.
 */
import { useEffect, useState } from 'react';
import { createDataSDK, gql } from '@salesforce/platform-sdk';

// Three aliases in one request — each becomes a key in the response
const QUERY = gql`
  query DashboardCounts {
    uiapi {
      query {
        accounts: Account(first: 50) {
          edges {
            node {
              Id
            }
          }
        }
        contacts: Contact(first: 50) {
          edges {
            node {
              Id
            }
          }
        }
        opportunities: Opportunity(first: 50) {
          edges {
            node {
              Id
            }
          }
        }
      }
    }
  }
`;

interface QueryResponse {
  uiapi: {
    query: {
      accounts: { edges: Array<{ node: { Id: string } }> };
      contacts: { edges: Array<{ node: { Id: string } }> };
      opportunities: { edges: Array<{ node: { Id: string } }> };
    };
  };
}

interface DashboardStats {
  accounts: number;
  contacts: number;
  opportunities: number;
}

export default function DashboardAliasedQueries() {
  const [stats, setStats] = useState<DashboardStats>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>();

  useEffect(() => {
    const fetchStats = async () => {
      const sdk = await createDataSDK();
      const result = await sdk.graphql?.query<QueryResponse>({ query: QUERY });

      if (result?.errors?.length) {
        throw new Error(
          result.errors.map((e: { message: string }) => e.message).join('; ')
        );
      }

      const query = result?.data?.uiapi?.query;
      setStats({
        accounts: query?.accounts?.edges?.length ?? 0,
        contacts: query?.contacts?.edges?.length ?? 0,
        opportunities: query?.opportunities?.edges?.length ?? 0,
      });
    };

    fetchStats()
      .catch(err => {
        setError(err instanceof Error ? err.message : 'Request failed');
      })
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <p className="text-sm">Loading…</p>;
  if (error) return <p className="text-destructive">{error}</p>;
  if (!stats) return null;

  return (
    <div className="flex gap-4 flex-wrap">
      <div className="w-1/3">
        <StatCard label="Accounts" count={stats.accounts} accent="border-l-primary" />
      </div>
      <div className="w-1/3">
        <StatCard label="Contacts" count={stats.contacts} accent="border-l-rose-400" />
      </div>
      <div className="w-1/3">
        <StatCard label="Opportunities" count={stats.opportunities} accent="border-l-amber-400" />
      </div>
    </div>
  );
}

function StatCard({ label, count, accent }: { label: string; count: number; accent: string }) {
  return (
    <div className={`rounded-md border border-border bg-card p-4 text-center shadow-sm border-l-4 ${accent}`}>
      <p className="text-2xl font-bold tabular-nums">{count}</p>
      <p className="text-xs text-muted-foreground mt-1">{label}</p>
    </div>
  );
}

// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/integration/dashboard-aliased-queries/dashboard-aliased-queries.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, signal } from '@angular/core';
import { createDataSDK, gql } from '@salesforce/platform-sdk';
import { StatCardComponent } from '../../../components/recipe/stat-card/stat-card';

// Three aliases in one request — each becomes its own key in the response,
// so a whole dashboard's counts come back in a single round-trip.
const QUERY = gql`
	query DashboardCounts {
		uiapi {
			query {
				accounts: Account(first: 50) {
					edges {
						node {
							Id
						}
					}
				}
				contacts: Contact(first: 50) {
					edges {
						node {
							Id
						}
					}
				}
				opportunities: Opportunity(first: 50) {
					edges {
						node {
							Id
						}
					}
				}
			}
		}
	}
`;

/**
 * Dashboard with Aliased Queries
 *
 * Fetches Accounts, Contacts, and Opportunities in a single aliased request and
 * transforms the results into stat cards — the dashboard pattern built on the
 * aliased multi-object query.
 *
 * LWC equivalent: multiple @wire calls, or an Apex method returning a wrapper
 * with a count per object.
 */
@Component({
	selector: 'app-dashboard-aliased-queries',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [StatCardComponent],
	templateUrl: './dashboard-aliased-queries.html',
})
export class DashboardAliasedQueriesComponent implements OnInit {
	protected readonly stats = signal<DashboardStats | undefined>(undefined);
	protected readonly loading = signal(true);
	protected readonly error = signal<string | undefined>(undefined);

	// One card descriptor per object — the template loops over these instead of
	// repeating the card markup three times.
	protected readonly cards = computed(() => {
		const s = this.stats();
		if (!s) return [];
		return [
			{ label: 'Accounts', count: s.accounts, accent: 'border-l-primary' },
			{ label: 'Contacts', count: s.contacts, accent: 'border-l-rose-400' },
			{ label: 'Opportunities', count: s.opportunities, accent: 'border-l-amber-400' },
		];
	});

	async ngOnInit(): Promise<void> {
		try {
			const sdk = await createDataSDK();
			const result = await sdk.graphql?.query<QueryResponse>({ query: QUERY });

			if (result?.errors?.length) {
				throw new Error(result.errors.map((e: { message: string }) => e.message).join('; '));
			}

			const query = result?.data?.uiapi?.query;
			this.stats.set({
				accounts: query?.accounts?.edges?.length ?? 0,
				contacts: query?.contacts?.edges?.length ?? 0,
				opportunities: query?.opportunities?.edges?.length ?? 0,
			});
		} catch (err) {
			this.error.set(err instanceof Error ? err.message : 'Request failed');
		} finally {
			this.loading.set(false);
		}
	}
}

interface QueryResponse {
	uiapi: {
		query: {
			accounts: { edges: { node: { Id: string } }[] };
			contacts: { edges: { node: { Id: string } }[] };
			opportunities: { edges: { node: { Id: string } }[] };
		};
	};
}

interface DashboardStats {
	accounts: number;
	contacts: number;
	opportunities: number;
}
