// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/hello/parent-to-child/parent-to-child.ts
import { ChangeDetectionStrategy, Component, OnInit, input, signal } from '@angular/core';
import { createDataSDK, gql } from '@salesforce/platform-sdk';

const QUERY = gql`
	query TwoAccounts {
		uiapi {
			query {
				Account(first: 2, orderBy: { Name: { order: ASC } }) {
					edges {
						node {
							Id
							Name @optional {
								value
							}
							Industry @optional {
								value
							}
						}
					}
				}
			}
		}
	}
`;

/**
 * A pure display child. It receives its data through signal inputs and never
 * fetches anything itself — the Angular equivalent of an LWC @api property.
 */
@Component({
	selector: 'app-account-card',
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './account-card.html',
})
export class AccountCardComponent {
	readonly name = input.required<string>();
	readonly industry = input<string | null>(null);
}

/**
 * Parent-to-Child (Inputs) with Salesforce Data
 *
 * The parent fetches Accounts via GraphQL and passes each one to a child
 * component through inputs. The child is a pure display component.
 *
 * LWC equivalent: child components receive data via @api properties set by the
 * parent in the template. Angular uses signal inputs — the same idea.
 *
 * @see ChildToParentComponent — communicating from child back to parent
 */
@Component({
	selector: 'app-parent-to-child',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [AccountCardComponent],
	templateUrl: './parent-to-child.html',
})
export class ParentToChildComponent implements OnInit {
	protected readonly accounts = signal<AccountFields[] | undefined>(undefined);
	protected readonly error = signal<string | undefined>(undefined);

	async ngOnInit(): Promise<void> {
		try {
			const sdk = await createDataSDK();
			const result = await sdk.graphql?.query<QueryResponse>({ query: QUERY });

			if (result?.errors?.length) {
				throw new Error(
					result.errors.map((e: { message: string }) => e.message).join('; '),
				);
			}

			const edges = result?.data?.uiapi?.query?.Account?.edges ?? [];
			this.accounts.set(
				edges.map((edge) => ({
					id: edge.node.Id,
					name: edge.node.Name?.value ?? 'Unknown',
					industry: edge.node.Industry?.value ?? null,
				})),
			);
		} catch (err) {
			this.error.set(err instanceof Error ? err.message : 'Request failed');
		}
	}
}

interface QueryResponse {
	uiapi: {
		query: {
			Account: {
				edges: {
					node: {
						Id: string;
						Name: { value: string | null };
						Industry: { value: string | null };
					};
				}[];
			};
		};
	};
}

interface AccountFields {
	id: string;
	name: string;
	industry: string | null;
}

// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/hello/ParentToChild.tsx
/**
 * Parent-to-Child (Props) with Salesforce Data
 *
 * The parent fetches Accounts via GraphQL and passes each one to a child
 * component as props. The child is a pure display component.
 *
 * LWC equivalent: child components receive data via @api properties set
 * by the parent in the template. React uses props — the same concept,
 * different syntax.
 *
 * @see ChildToParent — communicating from child back to parent via callbacks
 */
import { useEffect, useState } from 'react';
import { createDataSDK, gql } from '@salesforce/platform-sdk';

const QUERY = gql`
  query TwoAccounts {
    uiapi {
      query {
        Account(first: 2, orderBy: { Name: { order: ASC } }) {
          edges {
            node {
              Id
              Name @optional {
                value
              }
              Industry @optional {
                value
              }
            }
          }
        }
      }
    }
  }
`;

interface QueryResponse {
  uiapi: {
    query: {
      Account: {
        edges: Array<{
          node: {
            Id: string;
            Name: { value: string | null };
            Industry: { value: string | null };
          };
        }>;
      };
    };
  };
}

interface AccountFields {
  id: string;
  name: string;
  industry: string | null;
}

export default function ParentToChild() {
  const [accounts, setAccounts] = useState<AccountFields[]>();
  const [error, setError] = useState<string>();

  useEffect(() => {
    const fetchAccounts = async () => {
      const sdk = await createDataSDK();
      const result = await sdk.graphql?.query<QueryResponse>({ query: QUERY });

      if (result?.errors?.length) {
        throw new Error(
          result.errors.map((e: { message: string }) => e.message).join('; ')
        );
      }

      const edges = result?.data?.uiapi?.query?.Account?.edges ?? [];
      setAccounts(
        edges
          .map(edge => edge?.node)
          .filter(Boolean)
          .map(node => ({
            id: node.Id,
            name: node.Name?.value ?? 'Unknown',
            industry: node.Industry?.value ?? null,
          }))
      );
    };

    fetchAccounts().catch(err => {
      setError(err instanceof Error ? err.message : 'Request failed');
    });
  }, []);

  if (error) return <p className="text-destructive">{error}</p>;
  if (!accounts) return <p className="text-sm">Loading…</p>;

  return (
    <div className="flex gap-4">
      {/* Each Account is passed to a child via props — not fetched again */}
      {accounts.map(account => (
        <div key={account.id}>
          <AccountCard name={account.name} industry={account.industry} />
        </div>
      ))}
    </div>
  );
}

interface AccountCardProps {
  name: string;
  industry: string | null;
}

function AccountCard({ name, industry }: AccountCardProps) {
  return (
    <div className="rounded-md border border-border bg-card p-4">
      <p className="text-sm font-medium">
        <strong>{name}</strong>
      </p>
      <p className="text-xs text-muted-foreground">
        {industry ?? 'No Industry'}
      </p>
    </div>
  );
}
