// force-app/main/angular-recipes/uiBundles/angularRecipes/src/app/recipes/salesforce-apis/display-current-user/display-current-user.ts
import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { createDataSDK } from '@salesforce/platform-sdk';

/**
 * Display Current User
 *
 * Fetches the current user from the Chatter REST endpoint /users/me via
 * sdk.fetch — plain JSON, no UIAPI { value } wrappers. This is the first recipe
 * to use sdk.fetch (REST) rather than sdk.graphql.
 *
 * LWC equivalent: import userId from '@salesforce/user/Id', then @wire(getRecord)
 * on the User object for fields like Name and Email.
 *
 * @see UiApiRestComponent — the UI API REST endpoints
 */
@Component({
	selector: 'app-display-current-user',
	changeDetection: ChangeDetectionStrategy.OnPush,
	templateUrl: './display-current-user.html',
})
export class DisplayCurrentUserComponent implements OnInit {
	protected readonly user = signal<ChatterUser | undefined>(undefined);
	protected readonly error = signal<string | undefined>(undefined);

	async ngOnInit(): Promise<void> {
		try {
			const sdk = await createDataSDK();
			const res = await sdk.fetch?.('/services/data/v66.0/chatter/users/me');
			if (!res?.ok) {
				throw new Error(`Failed to fetch current user (${res?.status})`);
			}
			// res.json() is untyped; annotate the destination rather than casting.
			const data: ChatterUser = await res.json();
			this.user.set(data);
		} catch (err) {
			this.error.set(err instanceof Error ? err.message : 'Request failed');
		}
	}
}

interface ChatterUser {
	displayName: string;
	email: string;
}

// force-app/main/react-recipes/uiBundles/reactRecipes/src/recipes/salesforce-apis/DisplayCurrentUser.tsx
/**
 * Display Current User
 *
 * Fetches the current user via the Chatter REST endpoint /users/me
 * using DataSDK.fetch. Returns plain JSON with displayName and email.
 *
 * LWC equivalent: import userId from '@salesforce/user/Id' to get the
 * current user's ID, then @wire(getRecord) on the User object to fetch
 * fields like Name and Email.
 *
 * @see ConnectApi — fetching Chatter feed data via Connect API
 */
import { useEffect, useState } from 'react';
import { createDataSDK } from '@salesforce/platform-sdk';

interface ChatterUser {
  displayName: string;
  email: string;
}

export default function DisplayCurrentUser() {
  const [user, setUser] = useState<ChatterUser>();
  const [error, setError] = useState<string>();

  useEffect(() => {
    const fetchUser = async () => {
      const sdk = await createDataSDK();
      const res = await sdk.fetch?.('/services/data/v66.0/chatter/users/me');
      if (!res?.ok) throw new Error(`Failed to fetch current user (${res?.status})`);
      const data: ChatterUser = await res.json();
      setUser(data);
    };

    fetchUser().catch(err => {
      setError(err instanceof Error ? err.message : 'Request failed');
    });
  }, []);

  if (error) return <p className="text-destructive">{error}</p>;
  if (!user) return <p className="text-sm">Loading…</p>;

  return (
    <div>
      <p className="text-lg font-semibold">{user.displayName}</p>
      <p className="text-xs text-muted-foreground">{user.email}</p>
    </div>
  );
}
